# Projects required for tooling around qproxy, but are
# not imported by project itself
required = [
    "github.com/favadi/protoc-go-inject-tag",
    "github.com/pquerna/ffjson",
    "github.com/golang/glog",
    "google.golang.org/genproto/googleapis/api/annotations",
    "github.com/ghodss/yaml",
    "github.com/golang/protobuf/protoc-gen-go",
    "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.5.1"

[[override]]
  branch = "master"
  name = "github.com/pquerna/ffjson"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.7.0"
